on:
  push:
    branches:
      - main
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/maridaje-api-prod:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/maridaje-api-prod:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: soa41d-project1
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/maridaje-api-prod:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            cpu: 1
            ip-address: Public
            memory: 1
            ports: 80
            name: maridaje-app
            location: 'east us'
            environment-variables: | 
              'OPENAI_API_KEY'=${{ secrets.OPENAI_API_KEY }}
